# -*- coding: utf-8 -*-
"""atm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/ChattrapornAk/d71f94b7d48c085cda49818039c4eee2/atm.ipynb

## **OOP ATM**
"""

import pandas as pd
import random

class ATM:
    def __init__(self, username, bank, amount):
        self.username = username
        self.bank = bank
        self.amount = amount

    def __str__(self):
        return f"{self.username} uses {self.bank} and has {self.amount} THB in an account."

    def check_balance(self):
        print(f"Balance: {self.amount} THB")

    def deposit(self, saving):
        self.amount += saving
        print(f"Deposit {saving} THB successfully.")

    def withdraw(self, saving):
        self.amount -= saving
        print(f"Withdraw {saving} THB successfully.")

    def transfer(self, saving, username):
        self.amount -= saving
        print(f"Transfer {saving} THB to {self.username} successfully.")

    def get_otp(self):
        self.otp = random.randint(1000, 9999)
        print(f"Your OTP request: {self.otp}.")

    def check_otp(self, otp):
        if otp == self.otp:
            print("OTP is correct.")
        else:
            print("OTP is incorrect.")

my_account = ATM("chattraporn", "scb", 500)
print(my_account)
my_account.check_balance()
my_account.deposit(100)
my_account.withdraw(200)
my_account.check_balance()
my_account.transfer(300, "chattraporn")
my_account.get_otp()
my_account.check_otp(1234)
my_account.check_balance()

