# -*- coding: utf-8 -*-
"""RequestAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-lYQPUkXJ-OXfBcw1i-RN_2Y4sK7SnI9

## **Request APL json placeholder**
"""

# import library request for request API
# import library time for setting running time in loop
import requests
import time

# create names list for collect result
names = []

# use for loop to request API each json data: for 5 times
for i in range(5):
    url = f"https://jsonplaceholder.typicode.com/users/{i+1}" # add number in each loop to get data
    response = requests.get(url) # request API
    response_json = response.json() # change data to json form
    names.append(response_json["name"]) # select name add added to names list
    print(f"Success:{i+1}") # print success in each run data
    time.sleep(1) # setting run time: 1 second

print(names)

